import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/header";
import Footer from "@/components/shared/footer";
import { Toaster } from "sonner";
import LanguageProvider from "@/components/providers/LanguageProvider";

// Poppins fontini kerakli og‘irliklar (weights) bilan chaqirish
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "900"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <LanguageProvider>
          <Header />
          <Toaster />
          <div className="min-h-[calc(100vh-242px)]">
            {children}
          </div>
          <Footer />
        </LanguageProvider>

      </body>
    </html>
  );
}
